// <auto-generated />
namespace OopRestaurant201810.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addLocationdatabasetableandTablecolumnproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLocationdatabasetableandTablecolumnproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201811031242364_add Location database table and Table.column property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
