// <auto-generated />
namespace OopRestaurant201810.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTablesdatabasetabla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTablesdatabasetabla));
        
        string IMigrationMetadata.Id
        {
            get { return "201811031203344_add Tables database tabla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
